const C=document.getElementById('gl'),G=C.getContext('webgl',{antialias:false});if(!G)alert('WebGL не поддерживается');
let W=innerWidth,H=innerHeight;function resize(){C.width=Math.max(1,innerWidth*devicePixelRatio);C.height=Math.max(1,innerHeight*devicePixelRatio);G.viewport(0,0,C.width,C.height)}addEventListener('resize',resize);resize();
const vs=`attribute vec3 p;attribute vec3 n;uniform mat4 mvp,m;uniform vec3 sun;varying float l;varying vec3 vN;varying vec3 vP;void main(){vN=mat3(m)*n;vP=(m*vec4(p,1.)).xyz;l=max(.18,dot(normalize(vN),normalize(sun))*.8+.2);gl_Position=mvp*vec4(p,1.)}`;
const fs=`precision mediump float;uniform vec4 col;varying float l;varying vec3 vN;varying vec3 vP;void main(){float fog=clamp(length(vP)/55.,0.,1.);vec3 c=col.rgb*l;c=mix(c,vec3(.025,.035,.05),fog*.55);gl_FragColor=vec4(c,col.a)}`;
function sh(t,s){let x=G.createShader(t);G.shaderSource(x,s);G.compileShader(x);return x}let P=G.createProgram(),A=sh(G.VERTEX_SHADER,vs),B=sh(G.FRAGMENT_SHADER,fs);G.attachShader(P,A);G.attachShader(P,B);G.linkProgram(P);G.useProgram(P);
const loc={p:G.getAttribLocation(P,'p'),n:G.getAttribLocation(P,'n'),mvp:G.getUniformLocation(P,'mvp'),m:G.getUniformLocation(P,'m'),col:G.getUniformLocation(P,'col'),sun:G.getUniformLocation(P,'sun')};
function mat(){return new Float32Array(16)}function I(o=mat()){o[0]=o[5]=o[10]=o[15]=1;return o}function mul(a,b){let o=mat();for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[c+r*4]=a[r*4]*b[c]+a[r*4+1]*b[c+4]+a[r*4+2]*b[c+8]+a[r*4+3]*b[c+12];return o}function T(x,y,z){let m=I();m[12]=x;m[13]=y;m[14]=z;return m}function S(x,y,z){let m=I();m[0]=x;m[5]=y;m[10]=z;return m}function Rx(a){let m=I(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}function Ry(a){let m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}function persp(fovy,asp,n,f){let t=1/Math.tan(fovy/2),o=mat();o[0]=t/asp;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
function lookAt(ex,ey,ez,cx,cy,cz){let z=[ex-cx,ey-cy,ez-cz],zl=Math.hypot(...z);z=z.map(v=>v/zl);let x=[0,1,0];x=[x[1]*z[2]-x[2]*z[1],x[2]*z[0]-x[0]*z[2],x[0]*z[1]-x[1]*z[0]];let xl=Math.hypot(...x);x=x.map(v=>v/xl);let y=[z[1]*x[2]-z[2]*x[1],z[2]*x[0]-z[0]*x[2],z[0]*x[1]-z[1]*x[0]],m=I();m[0]=x[0];m[1]=y[0];m[2]=z[0];m[4]=x[1];m[5]=y[1];m[6]=z[1];m[8]=x[2];m[9]=y[2];m[10]=z[2];m[12]=-(x[0]*ex+x[1]*ey+x[2]*ez);m[13]=-(y[0]*ex+y[1]*ey+y[2]*ez);m[14]=-(z[0]*ex+z[1]*ey+z[2]*ez);return m}
const cubeV=new Float32Array([-.5,-.5,.5,.5,-.5,.5,.5,.5,.5,-.5,.5,.5,-.5,-.5,-.5,-.5,.5,-.5,.5,.5,-.5,.5,-.5,-.5,-.5,-.5,.5,-.5,-.5,.5,-.5,.5,.5,.5,.5,.5,-.5,.5,.5,-.5,.5,-.5,-.5,-.5,-.5,.5,.5,-.5,.5,.5,.5,.5,-.5,.5,-.5,-.5,-.5,-.5,-.5,.5,-.5,.5,.5,-.5,.5,-.5,-.5,.5,-.5,-.5,-.5,-.5,-.5,-.5,.5,.5,-.5,.5,.5,.5,.5,.5,.5,-.5,.5,.5,-.5,.5,.5,-.5,.5,-.5]);
const cubeN=new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,1,0,0,1,0,0,1,0,0,1,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1]);
const cubeI=new Uint16Array([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23]);
function mesh(v,n,i){let o={vb:G.createBuffer(),nb:G.createBuffer(),ib:G.createBuffer(),cnt:i.length};G.bindBuffer(G.ARRAY_BUFFER,o.vb);G.bufferData(G.ARRAY_BUFFER,v,G.STATIC_DRAW);G.bindBuffer(G.ARRAY_BUFFER,o.nb);G.bufferData(G.ARRAY_BUFFER,n,G.STATIC_DRAW);G.bindBuffer(G.ELEMENT_ARRAY_BUFFER,o.ib);G.bufferData(G.ELEMENT_ARRAY_BUFFER,i,G.STATIC_DRAW);return o}const cube=mesh(cubeV,cubeN,cubeI);
function draw(m,scale,col,VP){let M=mul(m,S(...scale)),MVP=mul(VP,M);G.bindBuffer(G.ARRAY_BUFFER,cube.vb);G.vertexAttribPointer(loc.p,3,G.FLOAT,false,0,0);G.enableVertexAttribArray(loc.p);G.bindBuffer(G.ARRAY_BUFFER,cube.nb);G.vertexAttribPointer(loc.n,3,G.FLOAT,false,0,0);G.enableVertexAttribArray(loc.n);G.bindBuffer(G.ELEMENT_ARRAY_BUFFER,cube.ib);G.uniformMatrix4fv(loc.mvp,false,MVP);G.uniformMatrix4fv(loc.m,false,M);G.uniform4fv(loc.col,col);G.drawElements(G.TRIANGLES,cube.cnt,G.UNSIGNED_SHORT,0)}
const keys={};addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyR')reload()});addEventListener('keyup',e=>keys[e.code]=0);
let player={x:0,y:1.7,z:8,yaw:Math.PI,pitch:0,hp:100,ammo:30,reserve:120,reloading:false};let enemies=[];let bullets=[];let pickups=[];let wave=1,kills=0,state='menu';let last=0,shootHeld=false;
const walls=[[-12,1.5,0,1,3,28],[12,1.5,0,1,3,28],[-6,1.5,-12,12,3,1],[6,1.5,0,8,3,1],[0,1.5,12,24,3,1],[-3,1.5,-4,1,3,8],[3,1.5,-4,1,3,8]];
function spawnWave(){for(let i=0;i<wave+3;i++){let side=Math.random()<.5?-1:1;enemies.push({x:(Math.random()*8-4),z:-16-Math.random()*14,side,hp:60+wave*8,cd:0,hit:0})}msg('ВОЛНА '+wave)}
function msg(t){document.getElementById('msg').textContent=t;clearTimeout(msg.t);msg.t=setTimeout(()=>document.getElementById('msg').textContent='',1400)}
function reload(){if(player.reloading||player.ammo>=30||player.reserve<=0)return;player.reloading=true;msg('ПЕРЕЗАРЯДКА');setTimeout(()=>{let n=Math.min(30-player.ammo,player.reserve);player.ammo+=n;player.reserve-=n;player.reloading=false},850)}
function fire(){if(state!=='play'||player.reloading||player.ammo<=0){if(player.ammo<=0)reload();return}player.ammo--;let dx=Math.sin(player.yaw),dz=Math.cos(player.yaw);bullets.push({x:player.x,y:player.y-0.1,z:player.z,vx:dx*26,vy:Math.sin(player.pitch)*26,vz:dz*26,life:1});}
function enemyHit(b){let best=null,bd=99;for(const e of enemies){let d=Math.hypot(b.x-e.x,b.z-e.z);if(d<1.25&&Math.abs(b.y-1.3)<1.3&&d<bd){bd=d;best=e}}return best}
function collide(x,z){for(const w of walls){if(Math.abs(x-w[0])<w[3]/2+.35&&Math.abs(z-w[2])<w[5]/2+.35)return true}return false}
function mobile(){return matchMedia('(pointer:coarse)').matches||innerWidth<800}
const joy=document.getElementById('joy'),knob=document.getElementById('knob'),look=document.getElementById('look');let jt=null,jx=0,jy=0,lt=null,lx=0,ly=0;joy.onpointerdown=e=>{jt=e.pointerId;joy.setPointerCapture(jt)};joy.onpointermove=e=>{if(e.pointerId!==jt)return;let r=joy.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),d=Math.hypot(x,y),m=45;if(d>m){x*=m/d;y*=m/d}jx=x/m;jy=y/m;knob.style.transform=`translate(${x}px,${y}px)`};joy.onpointerup=joy.onpointercancel=e=>{if(e.pointerId===jt){jt=null;jx=jy=0;knob.style.transform='translate(0,0)'}};look.onpointerdown=e=>{lt=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(lt)};look.onpointermove=e=>{if(e.pointerId!==lt)return;let dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;player.yaw+=dx*.008;player.pitch=Math.max(-1.25,Math.min(1.25,player.pitch+dy*.006))};look.onpointerup=look.onpointercancel=e=>lt=null;document.getElementById('fire').onpointerdown=e=>{shootHeld=true};document.getElementById('fire').onpointerup=()=>shootHeld=false;document.getElementById('reload').onpointerdown=reload;
addEventListener('mousedown',e=>{if(state==='play'&&e.button===0){shootHeld=true;if(!mobile())C.requestPointerLock?.()}});addEventListener('mouseup',e=>{if(e.button===0)shootHeld=false});addEventListener('mousemove',e=>{if(document.pointerLockElement===C){player.yaw+=e.movementX*.0022;player.pitch=Math.max(-1.25,Math.min(1.25,player.pitch+e.movementY*.0022))}});
function reset(){player={x:0,y:1.7,z:8,yaw:Math.PI,pitch:0,hp:100,ammo:30,reserve:120,reloading:false};enemies=[];bullets=[];wave=1;kills=0;state='play';spawnWave()}
document.getElementById('startBtn').onclick=()=>{document.getElementById('start').style.display='none';reset()};
function update(dt){if(state!=='play')return;let sp=6,dx=0,dz=0;if(keys.KeyW)dz-=1;if(keys.KeyS)dz+=1;if(keys.KeyA)dx-=1;if(keys.KeyD)dx+=1;if(jx||jy){dx=jx;dz=jy}let cy=Math.cos(player.yaw),sy=Math.sin(player.yaw),vx=dx*cy-dz*sy,vz=dx*sy+dz*cy,nx=player.x+vx*sp*dt,nz=player.z+vz*sp*dt;if(!collide(nx,player.z))player.x=nx;if(!collide(player.x,nz))player.z=nz;player.x=Math.max(-10.7,Math.min(10.7,player.x));player.z=Math.max(-11.5,Math.min(10.5,player.z));if(shootHeld&&(last<performance.now()-120))fire();for(let b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.z+=b.vz*dt;b.life-=dt;let e=enemyHit(b);if(e){e.hp-=34;b.life=0;if(e.hp<=0){kills++;if(Math.random()<.25)pickups.push({x:e.x,z:e.z,type:'ammo'});}}}bullets=bullets.filter(b=>b.life>0&&Math.abs(b.x)<20&&Math.abs(b.z)<40&&b.y>-1&&b.y<5);for(let e of enemies){let dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz);e.cd-=dt;if(d>2.0){let ex=e.x+dx/d*(1.5+wave*.04)*dt,ez=e.z+dz/d*(1.5+wave*.04)*dt;if(!collide(ex,e.z))e.x=ex;if(!collide(e.x,ez))e.z=ez}else if(e.cd<=0){e.cd=.8+Math.random()*.7;player.hp-=5;if(player.hp<=0){state='dead';msg('ТЫ ПОГИБ. Нажми ENTER');}}}enemies=enemies.filter(e=>e.hp>0&&e.x>-30&&e.x<30);for(let p of pickups){if(Math.hypot(player.x-p.x,player.z-p.z)<1.1&&p.type==='ammo'){player.reserve+=40;p.dead=1;msg('+40 ПАТРОНОВ')}}pickups=pickups.filter(p=>!p.dead);if(enemies.length===0){wave++;setTimeout(()=>state==='play'&&spawnWave(),1100)}}
addEventListener('keydown',e=>{if(e.code==='Enter'&&state==='dead'){document.getElementById('start').style.display='none';reset()}});
function render(){G.clearColor(.015,.02,.03,1);G.enable(G.DEPTH_TEST);G.clear(G.COLOR_BUFFER_BIT|G.DEPTH_BUFFER_BIT);let VP=mul(persp(Math.PI/3,C.width/C.height,.05,100),lookAt(player.x,player.y,player.z,player.x+Math.sin(player.yaw)*Math.cos(player.pitch),player.y+Math.sin(player.pitch),player.z+Math.cos(player.yaw)*Math.cos(player.pitch)));G.uniform3f(loc.sun,-.4,1,.35);draw(T(0,-.35,0),[24,.5,30],[.12,.15,.18,1],VP);for(const w of walls)draw(T(w[0],w[1],w[2]),[w[3],w[4],w[5]],[.20,.23,.28,1],VP);for(let e of enemies)draw(mul(T(e.x,1.3,e.z),Ry(performance.now()*.001)),[1,2.2,1],[.65,.12,.09,1],VP);for(let p of pickups)draw(T(p.x,.35,p.z),[.5,.5,.5],[.1,.6,1,1],VP);for(let b of bullets)draw(T(b.x,b.y,b.z),[.12,.12,.45],[1,.75,.15,1],VP);document.getElementById('hp').textContent='HP '+Math.max(0,player.hp|0);document.getElementById('ammo').textContent=`AMMO ${player.ammo} / ${player.reserve}`;document.getElementById('wave').textContent='WAVE '+wave}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
